##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
    web:
        container_name: codesai_tdd_php
        image: epcallan/phpunit-php7
        volumes:
          - ".:/app"
        depends_on:
          - db
        working_dir: /app

    db:
        container_name: codesai_tdd_db
        image: mysql:5.7
        ports:
          - "3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=codesai
        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"
